### ISSUE TITLE
rui-card should submit on pressing enter

### ISSUE THREAD

**Issue by jdl031** [100health/rui-components#23]

**Comment by tobalsgithub** [comment]
Points:
* Update js for directive

**Comment by tobalsgithub** [comment]
@jdl031, is there a pul request for this?

**Comment by jdl031** [comment]
Forget to start with the pull request workflow. I'll get it fixed up tonight and hopefully @ajkitson can do the review. Will have 1 PR for both this issue and the creation of rui-sidenav
